package com.sempra.model;
// Generated Oct 22, 2014 3:20:46 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */

public class Book  implements java.io.Serializable {


     private Integer id;
     private String author;
     private String evaluation;
     private String publisher;
     private String isbn;
     private Integer pages;
     private String title;

    public Book() {
    }

    public Book(String author, String evaluation, String publisher, String isbn, Integer pages, String title) {
       this.author = author;
       this.evaluation = evaluation;
       this.publisher = publisher;
       this.isbn = isbn;
       this.pages = pages;
       this.title = title;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="author", length=45)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="evaluation", length=45)
    public String getEvaluation() {
        return this.evaluation;
    }
    
    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation;
    }

    
    @Column(name="publisher", length=45)
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    
    @Column(name="isbn", length=45)
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    
    @Column(name="pages")
    public Integer getPages() {
        return this.pages;
    }
    
    public void setPages(Integer pages) {
        this.pages = pages;
    }

    
    @Column(name="title", length=45)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


